


text
	
	<<date This >>
	
	
	
endtext






*- 
#INCLUDE tests\consta

do nameprogram.prg

do foxcodeplus.exe


*-
Thisform.


local xxx as "excel.application"
xxx.ActiveCell
	

*-
xxx = createobject("excel.application")
xxx

with xxx
	
endwith	


*- nao é possivel obter os membros da classe informada em write-time
loBuider = newobject(lcClassName,"tests\b.prg")
loBuider.


*- 
loBuider = newobject("myclass","tests\b.prg")
loBuider.BaseClass.


*-
lox = newobject("myclass","tests\costumers.vcx")
lox.


*-
loMyTest = newobject("cgo_combobox","testss\sgo_base.vcx")
loMyTest.


*-
loObj = newobject("calendar","tests\maintools.vcx")
loObj.


