Defi Clas sgo_teste2 as Form
	VON_prop1 = 0
	VON_prop2 = 0
	VON_prop3 = 0
	VON_prop4 = 0
 	
 	*** <summary>
 	*** Nome e idade do colaborador
 	*** </summary>
 	*** <param name="PLC_Nome">xxx</param>
 	*** <param name="PLC_Idade">yyy</param>
 	*** <remarks></remarks>
 	Protected Function FOC_Func2 
 		parameters PLC_Nome, PLC_Idade, PLN_Number
 		
 		
 		this.VON		
		
	Endfunc 
Enddefine  